name: demo-actions

on:
  #push:
  #  branches: main

  issues:
    types: opened
  
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
      - name: run a sample job
        run: echo Hello World  
      
      - name: upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-artifat
          path: ${{github.workspace}}
